<?php

namespace Database\Seeders;

use App\Models\ExcelFormula;
use Illuminate\Database\Seeder;

class ExcelFormulaSeeder extends Seeder
{
    public function run(): void
    {
        $formulas = [
            [
                'name' => 'VLOOKUP',
                'category' => 'Tìm kiếm',
                'syntax' => '=VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])',
                'description' => 'Tìm kiếm giá trị trong cột đầu tiên của bảng và trả về giá trị trong cùng hàng từ cột chỉ định.',
                'note' => 'range_lookup = FALSE để tìm chính xác, TRUE để tìm gần đúng (cần sắp xếp tăng dần). Chậm hơn INDEX+MATCH với bảng lớn.',
                'tags' => ['lookup', 'search', 'reference'],
            ],
            [
                'name' => 'XLOOKUP',
                'category' => 'Tìm kiếm',
                'syntax' => '=XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])',
                'description' => 'Thay thế hiện đại cho VLOOKUP/HLOOKUP. Tìm kiếm linh hoạt hơn, có thể trả về nhiều cột, hỗ trợ tìm ngược.',
                'note' => 'Chỉ có trên Excel 365/2021 và Google Sheets. Ưu tiên dùng thay VLOOKUP cho dự án mới.',
                'tags' => ['lookup', 'search', 'modern'],
            ],
            [
                'name' => 'INDEX + MATCH',
                'category' => 'Tìm kiếm',
                'syntax' => '=INDEX(return_range, MATCH(lookup_value, lookup_range, 0))',
                'description' => 'Combo mạnh nhất để tìm kiếm 2 chiều. Nhanh hơn VLOOKUP, không bị ảnh hưởng khi chèn/xóa cột.',
                'note' => 'MATCH trả về vị trí hàng, INDEX trả về giá trị tại vị trí đó. Tham số cuối MATCH = 0 là tìm chính xác.',
                'tags' => ['lookup', 'combo', 'advanced'],
            ],
            [
                'name' => 'FILTER',
                'category' => 'Tìm kiếm',
                'syntax' => '=FILTER(array, include, [if_empty])',
                'description' => 'Lọc dữ liệu theo điều kiện, trả về mảng động. Thay thế cho AutoFilter bằng công thức.',
                'note' => 'Kết hợp nhiều điều kiện bằng * (AND) hoặc + (OR).',
                'example' => '=FILTER(A2:C100, B2:B100="Hà Nội", "Không có")',
                'tags' => ['filter', 'array', 'dynamic'],
            ],
            [
                'name' => 'SUMIF',
                'category' => 'Thống kê',
                'syntax' => '=SUMIF(range, criteria, [sum_range])',
                'description' => 'Tính tổng các ô thỏa mãn điều kiện. Nếu bỏ sum_range, tính tổng chính range đó.',
                'note' => 'criteria có thể là: số, text, wildcard (*,?), biểu thức (">100"). Dùng SUMIFS cho nhiều điều kiện.',
                'tags' => ['sum', 'conditional', 'statistics'],
            ],
            [
                'name' => 'SUMIFS',
                'category' => 'Thống kê',
                'syntax' => '=SUMIFS(sum_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)',
                'description' => 'Tính tổng với nhiều điều kiện. Thứ tự tham số khác SUMIF: sum_range đứng đầu.',
                'note' => 'Tối đa 127 cặp criteria. Các criteria_range phải cùng kích thước với sum_range.',
                'tags' => ['sum', 'multi-condition', 'statistics'],
            ],
            [
                'name' => 'COUNTIFS',
                'category' => 'Thống kê',
                'syntax' => '=COUNTIFS(criteria_range1, criteria1, [criteria_range2, criteria2], ...)',
                'description' => 'Đếm số ô thỏa mãn nhiều điều kiện cùng lúc.',
                'note' => 'Thường dùng với điều kiện ngày: ">="&A1.',
                'tags' => ['count', 'multi-condition', 'statistics'],
            ],
            [
                'name' => 'AVERAGEIFS',
                'category' => 'Thống kê',
                'syntax' => '=AVERAGEIFS(average_range, criteria_range1, criteria1, ...)',
                'description' => 'Tính trung bình cộng với nhiều điều kiện.',
                'note' => 'Bỏ qua các ô text và ô trống trong average_range khi tính.',
                'tags' => ['average', 'multi-condition', 'statistics'],
            ],
            [
                'name' => 'UNIQUE',
                'category' => 'Thống kê',
                'syntax' => '=UNIQUE(array, [by_col], [exactly_once])',
                'description' => 'Lọc danh sách loại bỏ giá trị trùng lặp. Trả về mảng động (spill), chỉ cần nhập 1 ô.',
                'note' => 'Chỉ có Excel 365/2021 và Google Sheets. Kết hợp với SORT: =SORT(UNIQUE(A2:A100))',
                'tags' => ['unique', 'array', 'dynamic'],
            ],
            [
                'name' => 'IF',
                'category' => 'Logic',
                'syntax' => '=IF(logical_test, value_if_true, value_if_false)',
                'description' => 'Trả về giá trị khác nhau tùy điều kiện đúng hay sai.',
                'note' => 'Lồng tối đa 64 IF trong nhau (Excel). Với nhiều điều kiện, dùng IFS hoặc SWITCH cho gọn hơn.',
                'tags' => ['logic', 'conditional', 'basic'],
            ],
            [
                'name' => 'IFS',
                'category' => 'Logic',
                'syntax' => '=IFS(condition1, value1, condition2, value2, ..., TRUE, default)',
                'description' => 'Kiểm tra nhiều điều kiện, trả về giá trị của điều kiện đúng đầu tiên. Thay thế IF lồng nhau.',
                'note' => 'Luôn thêm TRUE, "Khác" ở cuối để xử lý trường hợp không khớp điều kiện nào.',
                'tags' => ['logic', 'multi-condition'],
            ],
            [
                'name' => 'IFERROR',
                'category' => 'Logic',
                'syntax' => '=IFERROR(value, value_if_error)',
                'description' => 'Trả về value_if_error nếu công thức bị lỗi (#N/A, #VALUE!, #REF!...). Ngược lại trả về value.',
                'note' => 'Dùng để bẫy lỗi sạch UI.',
                'example' => '=IFERROR(VLOOKUP(...),"Không tìm thấy")',
                'tags' => ['logic', 'error-handling'],
            ],
            [
                'name' => 'CONCATENATE / CONCAT',
                'category' => 'Văn bản',
                'syntax' => '=CONCAT(text1, [text2], ...) hoặc =A1&" "&B1',
                'description' => 'Nối nhiều chuỗi văn bản lại với nhau. Dùng & tiện hơn cho trường hợp đơn giản.',
                'note' => 'CONCATENATE vẫn hoạt động nhưng đã deprecated. CONCAT là phiên bản mới. TEXTJOIN linh hoạt hơn khi có dấu phân cách.',
                'tags' => ['text', 'join', 'string'],
            ],
            [
                'name' => 'TEXTJOIN',
                'category' => 'Văn bản',
                'syntax' => '=TEXTJOIN(delimiter, ignore_empty, text1, [text2], ...)',
                'description' => 'Nối nhiều chuỗi với dấu phân cách tùy chọn, có thể bỏ qua ô trống.',
                'note' => 'ignore_empty = TRUE bỏ qua ô rỗng.',
                'example' => '=TEXTJOIN(", ", TRUE, A2:A10)',
                'tags' => ['text', 'join', 'delimiter'],
            ],
            [
                'name' => 'TEXT',
                'category' => 'Văn bản',
                'syntax' => '=TEXT(value, format_text)',
                'description' => 'Chuyển đổi số/ngày thành văn bản theo định dạng tùy chỉnh.',
                'note' => '=TEXT(A1,"dd/mm/yyyy") → "01/06/2025". =TEXT(1000000,"#,##0") → "1,000,000".',
                'tags' => ['text', 'format', 'convert'],
            ],
            [
                'name' => 'LEFT / RIGHT / MID',
                'category' => 'Văn bản',
                'syntax' => '=LEFT(text, num_chars) | =MID(text, start_num, num_chars)',
                'description' => 'Cắt chuỗi từ trái, phải, hoặc giữa. LEFT/RIGHT đơn giản, MID linh hoạt hơn.',
                'note' => 'Kết hợp với FIND/SEARCH để tách chuỗi động.',
                'example' => '=LEFT(A1, FIND(" ", A1)-1)',
                'tags' => ['text', 'substring', 'extract'],
            ],
            [
                'name' => 'TODAY / NOW',
                'category' => 'Ngày giờ',
                'syntax' => '=TODAY() | =NOW()',
                'description' => 'TODAY() trả về ngày hiện tại, NOW() trả về ngày + giờ hiện tại. Tự cập nhật khi file tính toán lại.',
                'note' => 'Kết quả là số serial. Dùng TEXT() hoặc format cell để hiển thị dạng ngày đọc được.',
                'tags' => ['date', 'current', 'volatile'],
            ],
            [
                'name' => 'DATEDIF',
                'category' => 'Ngày giờ',
                'syntax' => '=DATEDIF(start_date, end_date, unit)',
                'description' => 'Tính khoảng cách giữa 2 ngày theo đơn vị: "Y" (năm), "M" (tháng), "D" (ngày).',
                'note' => 'Hàm ẩn, không hiện trong autocomplete nhưng vẫn hoạt động.',
                'example' => '=DATEDIF(B2, TODAY(), "Y")',
                'tags' => ['date', 'difference', 'hidden'],
            ],
            [
                'name' => 'WORKDAY',
                'category' => 'Ngày giờ',
                'syntax' => '=WORKDAY(start_date, days, [holidays])',
                'description' => 'Tính ngày kết thúc sau N ngày làm việc (bỏ qua thứ 7, CN). Có thể thêm danh sách ngày nghỉ lễ.',
                'note' => 'WORKDAY.INTL cho phép tùy chỉnh ngày nghỉ cuối tuần khác.',
                'tags' => ['date', 'business-day', 'workday'],
            ],
            [
                'name' => 'ROUND / ROUNDUP / ROUNDDOWN',
                'category' => 'Toán học',
                'syntax' => '=ROUND(number, num_digits)',
                'description' => 'Làm tròn số. ROUND làm tròn thông thường, ROUNDUP luôn lên, ROUNDDOWN luôn xuống.',
                'note' => 'num_digits âm làm tròn sang phần nguyên. =ROUND(1234,-2) → 1200.',
                'tags' => ['math', 'round', 'precision'],
            ],
            [
                'name' => 'SUMPRODUCT',
                'category' => 'Toán học',
                'syntax' => '=SUMPRODUCT(array1, [array2], ...)',
                'description' => 'Nhân từng phần tử tương ứng của các mảng rồi cộng tổng. Cực mạnh để thay thế công thức mảng.',
                'note' => 'Dùng được như COUNTIFS/SUMIFS nhưng linh hoạt hơn.',
                'example' => '=SUMPRODUCT((A:A="X")*(B:B>100)*C:C)',
                'tags' => ['math', 'array', 'advanced'],
            ],
            [
                'name' => 'IMPORTRANGE',
                'category' => 'Google Sheets',
                'syntax' => '=IMPORTRANGE(spreadsheet_url, range_string)',
                'description' => 'Lấy dữ liệu từ một vùng (range) của một file Google Sheet khác, kể cả file khác hoàn toàn.',
                'note' => 'Lần đầu dùng phải bấm "Cho phép truy cập" (Allow access). range_string dạng "TênSheet!A1:D100".',
                'example' => '=IMPORTRANGE("https://docs.google.com/spreadsheets/d/abc123/edit", "Sheet1!A1:D100")',
                'tags' => ['google-sheets', 'cross-sheet', 'import'],
            ],
            [
                'name' => 'QUERY',
                'category' => 'Google Sheets',
                'syntax' => '=QUERY(data, query_string, [headers])',
                'description' => 'Truy vấn dữ liệu bằng cú pháp giống SQL (select, where, group by, order by, limit...). Cực mạnh để lọc/tổng hợp dữ liệu, kể cả từ IMPORTRANGE.',
                'note' => 'query_string dùng ngôn ngữ Google Visualization API, cột tham chiếu bằng chữ cái (Col1, Col2...) khi data là kết quả hàm khác.',
                'example' => '=QUERY(A1:D100, "select A, sum(C) where B = \'Hà Nội\' group by A", 1)',
                'tags' => ['google-sheets', 'sql', 'aggregate'],
            ],
            [
                'name' => 'ARRAYFORMULA',
                'category' => 'Google Sheets',
                'syntax' => '=ARRAYFORMULA(array_formula)',
                'description' => 'Áp dụng một công thức cho toàn bộ cột/vùng dữ liệu mà không cần kéo công thức xuống từng dòng.',
                'note' => 'Thường dùng cho cột tự động tính khi có dòng mới được thêm vào (kết hợp với phạm vi mở như A2:A).',
                'example' => '=ARRAYFORMULA(IF(A2:A="", "", B2:B*C2:C))',
                'tags' => ['google-sheets', 'array', 'auto-fill'],
            ],
            [
                'name' => 'GOOGLEFINANCE',
                'category' => 'Google Sheets',
                'syntax' => '=GOOGLEFINANCE(ticker, [attribute], [start_date], [end_date|num_days], [interval])',
                'description' => 'Lấy dữ liệu tài chính/giá cổ phiếu, tỷ giá theo thời gian thực hoặc lịch sử từ Google Finance.',
                'note' => 'Chỉ có trên Google Sheets. attribute mặc định là "price".',
                'example' => '=GOOGLEFINANCE("HOSE:VNM", "price")',
                'tags' => ['google-sheets', 'finance', 'realtime'],
            ],
            [
                'name' => 'SPARKLINE',
                'category' => 'Google Sheets',
                'syntax' => '=SPARKLINE(data, [options])',
                'description' => 'Vẽ biểu đồ nhỏ (đường, cột, thắng/thua...) ngay trong một ô, tiện để xem xu hướng nhanh.',
                'note' => 'options là object dạng {"charttype","line";"color","#22d3a0"}.',
                'example' => '=SPARKLINE(B2:M2, {"charttype","column"})',
                'tags' => ['google-sheets', 'chart', 'visualization'],
            ],
            [
                'name' => 'GOOGLETRANSLATE',
                'category' => 'Google Sheets',
                'syntax' => '=GOOGLETRANSLATE(text, [source_language], [target_language])',
                'description' => 'Dịch văn bản tự động sang ngôn ngữ khác bằng Google Translate ngay trong sheet.',
                'note' => 'Mã ngôn ngữ ISO 639-1, ví dụ "vi", "en". Bỏ trống source_language để tự nhận diện.',
                'example' => '=GOOGLETRANSLATE(A2, "vi", "en")',
                'tags' => ['google-sheets', 'text', 'translate'],
            ],
            [
                'name' => 'SPLIT',
                'category' => 'Google Sheets',
                'syntax' => '=SPLIT(text, delimiter, [split_by_each], [remove_empty_text])',
                'description' => 'Tách một chuỗi thành nhiều cột dựa trên ký tự phân tách, kết quả trải (spill) ra các ô bên phải.',
                'note' => 'Tương đương "Data > Split text to columns" nhưng dùng được trong công thức.',
                'example' => '=SPLIT(A2, ",")',
                'tags' => ['google-sheets', 'text', 'split'],
            ],
            [
                'name' => 'REGEXEXTRACT / REGEXMATCH / REGEXREPLACE',
                'category' => 'Google Sheets',
                'syntax' => '=REGEXEXTRACT(text, regex) | =REGEXMATCH(text, regex) | =REGEXREPLACE(text, regex, replacement)',
                'description' => 'Bộ 3 hàm xử lý văn bản bằng biểu thức chính quy (regex): trích xuất, kiểm tra khớp, thay thế.',
                'note' => 'Dùng regex chuẩn RE2 của Google. REGEXMATCH trả về TRUE/FALSE, hữu ích kết hợp với IF/FILTER.',
                'example' => '=REGEXEXTRACT(A2, "[0-9]+")',
                'tags' => ['google-sheets', 'text', 'regex'],
            ],
        ];

        foreach ($formulas as $formula) {
            ExcelFormula::updateOrCreate(['name' => $formula['name']], $formula);
        }
    }
}
